/**
 * Deterministic `.env` renderer for the setup wizard. Produces a file grouped
 * and commented like `.env.example`, containing exactly the values the wizard
 * resolved. Optional fields left `undefined` are omitted (the config schema
 * supplies their defaults).
 */

import { DELEVERAGE_DEFAULTS } from '../../src/config'

export interface EnvValues {
  // Chain / RPC
  CHAIN_ID: number
  RPC_URL: string
  // Pool + Safe/Zodiac (Safe + modifier are freshly deployed by the wizard)
  POOL_ADDRESS: `0x${string}`
  SAFE_ADDRESS: `0x${string}`
  ROLES_MODIFIER_ADDRESS: `0x${string}`
  ROLE_KEY: `0x${string}`
  // Bot signer — exactly one of a raw key or an encrypted keystore path
  BOT_PRIVATE_KEY?: `0x${string}`
  BOT_KEYSTORE_PATH?: string
  // Hedging parameters
  ASSET_INDEX: 0 | 1
  DELTA_THRESHOLD_BPS?: number
  TIMED_HEDGE_INTERVAL_MS?: number
  TIMED_HEDGE_MIN_DRIFT_BPS?: number
  DELTA_OFFSET_BPS?: number
  MAX_HEDGE_SLOTS?: number
  SLIPPAGE_BPS?: number
  // Price signal
  PRICE_SIGNAL_SOURCE?: string
  // Hedge venue
  HEDGE_VENUE?: string
  // Off-venue SFPM swap (prefilled from the deployments registry when available)
  SFPM_SWAP_PROVISIONED?: boolean
  SFPM_SWAP_ENABLED?: boolean
  SFPM_SWAP_POOL_VERSION?: string
  SFPM_SWAP_ADDRESS_V3?: `0x${string}`
  SFPM_SWAP_POOL_ADDRESS?: `0x${string}`
  SFPM_SWAP_POOL_ID?: string
  SFPM_SWAP_FEE?: number
  WETH_ADDRESS?: `0x${string}`
  MULTISEND_CALL_ONLY_ADDRESS?: `0x${string}`
  MULTISEND_UNWRAPPER_ADDRESS?: `0x${string}`
  // Emergency deleverager (burn-only role held by the bot)
  DELEVERAGER_ENABLED?: boolean
  // Loop
  POLL_INTERVAL_MS?: number
  ORACLE_POKE_ENABLED?: boolean
  DRY_RUN?: boolean
  // Optional
  UNISWAP_LP_OWNER?: `0x${string}`
  HEDGE_INCLUDE_LP?: boolean
  TELEGRAM_BOT_TOKEN?: string
  TELEGRAM_CHAT_ID?: string
}

interface Line {
  key: keyof EnvValues
  value: string | number | boolean | undefined
}

interface Section {
  heading: string
  lines: Line[]
}

function fmt(value: string | number | boolean): string {
  return String(value)
}

/**
 * Render a complete `.env` file body. Includes a banner noting it was
 * generated by `pnpm setup`.
 */
export function renderEnvFile(values: EnvValues): string {
  const sections: Section[] = [
    {
      heading: 'Chain / RPC',
      lines: [
        { key: 'CHAIN_ID', value: values.CHAIN_ID },
        { key: 'RPC_URL', value: values.RPC_URL },
      ],
    },
    {
      heading: 'Panoptic pool holding the options + hedge loans',
      lines: [{ key: 'POOL_ADDRESS', value: values.POOL_ADDRESS }],
    },
    {
      heading: 'Safe + Zodiac Roles (deployed by `pnpm setup`)',
      lines: [
        { key: 'SAFE_ADDRESS', value: values.SAFE_ADDRESS },
        { key: 'ROLES_MODIFIER_ADDRESS', value: values.ROLES_MODIFIER_ADDRESS },
        { key: 'ROLE_KEY', value: values.ROLE_KEY },
      ],
    },
    {
      heading: 'Bot signer — raw key, or a passphrase-encrypted keystore file',
      lines: [
        { key: 'BOT_PRIVATE_KEY', value: values.BOT_PRIVATE_KEY },
        { key: 'BOT_KEYSTORE_PATH', value: values.BOT_KEYSTORE_PATH },
      ],
    },
    {
      heading: 'Hedging parameters',
      lines: [
        { key: 'ASSET_INDEX', value: values.ASSET_INDEX },
        { key: 'DELTA_THRESHOLD_BPS', value: values.DELTA_THRESHOLD_BPS },
        { key: 'TIMED_HEDGE_INTERVAL_MS', value: values.TIMED_HEDGE_INTERVAL_MS },
        { key: 'TIMED_HEDGE_MIN_DRIFT_BPS', value: values.TIMED_HEDGE_MIN_DRIFT_BPS },
        { key: 'DELTA_OFFSET_BPS', value: values.DELTA_OFFSET_BPS },
        { key: 'MAX_HEDGE_SLOTS', value: values.MAX_HEDGE_SLOTS },
        { key: 'SLIPPAGE_BPS', value: values.SLIPPAGE_BPS },
      ],
    },
    {
      heading: 'Price signal source: pool-tick | uniswap-pool | cex',
      lines: [{ key: 'PRICE_SIGNAL_SOURCE', value: values.PRICE_SIGNAL_SOURCE }],
    },
    {
      heading: 'Hedge venue: in-pool',
      lines: [{ key: 'HEDGE_VENUE', value: values.HEDGE_VENUE }],
    },
    {
      heading:
        'Off-venue SFPM swap — route the hedge-netting swap through a cheaper pool ' +
        '(v3 only; emitted only after explicit provisioning). Flip SFPM_SWAP_ENABLED=true ' +
        'after a DRY_RUN validation.',
      lines: [
        { key: 'SFPM_SWAP_PROVISIONED', value: values.SFPM_SWAP_PROVISIONED },
        { key: 'SFPM_SWAP_ENABLED', value: values.SFPM_SWAP_ENABLED },
        { key: 'SFPM_SWAP_POOL_VERSION', value: values.SFPM_SWAP_POOL_VERSION },
        { key: 'SFPM_SWAP_ADDRESS_V3', value: values.SFPM_SWAP_ADDRESS_V3 },
        { key: 'SFPM_SWAP_POOL_ADDRESS', value: values.SFPM_SWAP_POOL_ADDRESS },
        { key: 'SFPM_SWAP_POOL_ID', value: values.SFPM_SWAP_POOL_ID },
        { key: 'SFPM_SWAP_FEE', value: values.SFPM_SWAP_FEE },
        { key: 'WETH_ADDRESS', value: values.WETH_ADDRESS },
        { key: 'MULTISEND_CALL_ONLY_ADDRESS', value: values.MULTISEND_CALL_ONLY_ADDRESS },
        { key: 'MULTISEND_UNWRAPPER_ADDRESS', value: values.MULTISEND_UNWRAPPER_ADDRESS },
      ],
    },
    {
      heading:
        'Emergency deleverager — burn-only role held by the bot. Tunables (schema ' +
        `defaults): DELEVERAGE_TRIGGER_MARGIN_BPS=${DELEVERAGE_DEFAULTS.TRIGGER_MARGIN_BPS}, ` +
        `DELEVERAGE_TARGET_MARGIN_BPS=${DELEVERAGE_DEFAULTS.TARGET_MARGIN_BPS}, ` +
        `DELEVERAGE_SLIPPAGE_BPS=${DELEVERAGE_DEFAULTS.SLIPPAGE_BPS}, ` +
        `DELEVERAGE_COOLDOWN_MS=${DELEVERAGE_DEFAULTS.COOLDOWN_MS}`,
      lines: [{ key: 'DELEVERAGER_ENABLED', value: values.DELEVERAGER_ENABLED }],
    },
    {
      heading: 'Loop',
      lines: [
        // Always emit the poll interval so it is visible + editable in .env
        // (falls back to the schema default when the wizard didn't set one).
        { key: 'POLL_INTERVAL_MS', value: values.POLL_INTERVAL_MS ?? 60_000 },
        { key: 'ORACLE_POKE_ENABLED', value: values.ORACLE_POKE_ENABLED ?? false },
        { key: 'DRY_RUN', value: values.DRY_RUN },
      ],
    },
    {
      heading:
        'Optional — Uniswap LP hedging. UNISWAP_LP_OWNER = extra LP-holding address (scanned with the Safe). HEDGE_INCLUDE_LP=true folds same-pair LP delta into the hedge (only when the LP subgraph is fresh); false = observe-only.',
      lines: [
        { key: 'UNISWAP_LP_OWNER', value: values.UNISWAP_LP_OWNER },
        { key: 'HEDGE_INCLUDE_LP', value: values.HEDGE_INCLUDE_LP },
      ],
    },
    {
      heading: 'Optional — Telegram notifications (both required together)',
      lines: [
        { key: 'TELEGRAM_BOT_TOKEN', value: values.TELEGRAM_BOT_TOKEN },
        { key: 'TELEGRAM_CHAT_ID', value: values.TELEGRAM_CHAT_ID },
      ],
    },
  ]

  const out: string[] = [
    '# ============================================================================',
    '# Hedger Bot configuration — generated by `pnpm setup`',
    '# Re-run `pnpm setup --force` to regenerate, or edit values by hand.',
    '# ============================================================================',
  ]

  for (const section of sections) {
    const rendered = section.lines
      .filter((l) => l.value !== undefined && l.value !== '')
      .map((l) => `${l.key}=${fmt(l.value as string | number | boolean)}`)
    if (rendered.length === 0) continue
    out.push('', `# --- ${section.heading} ---`, ...rendered)
  }

  return out.join('\n') + '\n'
}
