/**
 * Deterministic `.env` renderer for the setup wizard. Produces a file grouped
 * and commented like `.env.example`, containing exactly the values the wizard
 * resolved. Optional fields left `undefined` are omitted (the config schema
 * supplies their defaults).
 */

export interface EnvValues {
  // Chain / RPC
  CHAIN_ID: number
  RPC_URL: string
  // Pool + Safe/Zodiac (Safe + modifier are freshly deployed by the wizard)
  POOL_ADDRESS: `0x${string}`
  SAFE_ADDRESS: `0x${string}`
  ROLES_MODIFIER_ADDRESS: `0x${string}`
  ROLE_KEY: `0x${string}`
  // Bot signer — exactly one of a raw key or an encrypted keystore path
  BOT_PRIVATE_KEY?: `0x${string}`
  BOT_KEYSTORE_PATH?: string
  // Hedging parameters
  ASSET_INDEX: 0 | 1
  DELTA_THRESHOLD_BPS?: number
  MAX_HEDGE_SLOTS?: number
  SLIPPAGE_BPS?: number
  // Price signal
  PRICE_SIGNAL_SOURCE?: string
  // Hedge venue
  HEDGE_VENUE?: string
  // Loop
  POLL_INTERVAL_MS?: number
  DRY_RUN?: boolean
  // Optional
  TELEGRAM_BOT_TOKEN?: string
  TELEGRAM_CHAT_ID?: string
}

interface Line {
  key: keyof EnvValues
  value: string | number | boolean | undefined
}

interface Section {
  heading: string
  lines: Line[]
}

function fmt(value: string | number | boolean): string {
  return String(value)
}

/**
 * Render a complete `.env` file body. Includes a banner noting it was
 * generated by `pnpm setup`.
 */
export function renderEnvFile(values: EnvValues): string {
  const sections: Section[] = [
    {
      heading: 'Chain / RPC',
      lines: [
        { key: 'CHAIN_ID', value: values.CHAIN_ID },
        { key: 'RPC_URL', value: values.RPC_URL },
      ],
    },
    {
      heading: 'Panoptic pool holding the options + hedge loans',
      lines: [{ key: 'POOL_ADDRESS', value: values.POOL_ADDRESS }],
    },
    {
      heading: 'Safe + Zodiac Roles (deployed by `pnpm setup`)',
      lines: [
        { key: 'SAFE_ADDRESS', value: values.SAFE_ADDRESS },
        { key: 'ROLES_MODIFIER_ADDRESS', value: values.ROLES_MODIFIER_ADDRESS },
        { key: 'ROLE_KEY', value: values.ROLE_KEY },
      ],
    },
    {
      heading: 'Bot signer — raw key, or a passphrase-encrypted keystore file',
      lines: [
        { key: 'BOT_PRIVATE_KEY', value: values.BOT_PRIVATE_KEY },
        { key: 'BOT_KEYSTORE_PATH', value: values.BOT_KEYSTORE_PATH },
      ],
    },
    {
      heading: 'Hedging parameters',
      lines: [
        { key: 'ASSET_INDEX', value: values.ASSET_INDEX },
        { key: 'DELTA_THRESHOLD_BPS', value: values.DELTA_THRESHOLD_BPS },
        { key: 'MAX_HEDGE_SLOTS', value: values.MAX_HEDGE_SLOTS },
        { key: 'SLIPPAGE_BPS', value: values.SLIPPAGE_BPS },
      ],
    },
    {
      heading: 'Price signal source: pool-tick | uniswap-pool | cex',
      lines: [{ key: 'PRICE_SIGNAL_SOURCE', value: values.PRICE_SIGNAL_SOURCE }],
    },
    {
      heading: 'Hedge venue: in-pool | cross-pool-uniswap',
      lines: [{ key: 'HEDGE_VENUE', value: values.HEDGE_VENUE }],
    },
    {
      heading: 'Loop',
      lines: [
        // Always emit the poll interval so it is visible + editable in .env
        // (falls back to the schema default when the wizard didn't set one).
        { key: 'POLL_INTERVAL_MS', value: values.POLL_INTERVAL_MS ?? 60_000 },
        { key: 'DRY_RUN', value: values.DRY_RUN },
      ],
    },
    {
      heading: 'Optional — Telegram notifications (both required together)',
      lines: [
        { key: 'TELEGRAM_BOT_TOKEN', value: values.TELEGRAM_BOT_TOKEN },
        { key: 'TELEGRAM_CHAT_ID', value: values.TELEGRAM_CHAT_ID },
      ],
    },
  ]

  const out: string[] = [
    '# ============================================================================',
    '# Hedger Bot configuration — generated by `pnpm setup`',
    '# Re-run `pnpm setup --force` to regenerate, or edit values by hand.',
    '# ============================================================================',
  ]

  for (const section of sections) {
    const rendered = section.lines
      .filter((l) => l.value !== undefined && l.value !== '')
      .map((l) => `${l.key}=${fmt(l.value as string | number | boolean)}`)
    if (rendered.length === 0) continue
    out.push('', `# --- ${section.heading} ---`, ...rendered)
  }

  return out.join('\n') + '\n'
}
